### ISSUE TITLE
Widget basic command range do nothing

### ISSUE THREAD

**Issue by Basilic** [domogik/domoweb#54]
I have add a widget basic range, sensor and command as DT_Scalling.

The send button is disable and the sensor do nothing. If I add a sensor number I can see the sensor working.

If I use the rest url the device working and the sensor value of widget range display the value.

**Comment by jschaeke** [comment]
+1 for fix

**Comment by fritz-smh** [comment]
I will check this week

**Comment by fritz-smh** [comment]
Should be fixed now in develop branch.
Please check :)

**Comment by jschaeke** [comment]
Thanks a lot, I checked it immediately and yes it works! It is however still a little bit awkward as the button does not respond all too well; I have to select it multiple times before I can actually move it.
Here a video: https://goo.gl/photos/XZsE1xP4otGHSFbE9

**Comment by jschaeke** [comment]
2 issues remain with current version of the slider:
- you need to click the exact center of the dot in order to move it (Chrome), in IE the dot is a little square so not applicable
- in a mobile browser (Chrome on android/Chrome on IOS), you can move the slider but nothing happens -> an event capture missing?

**Comment by fritz-smh** [comment]
should be better now. Can you test ?

**Comment by jschaeke** [comment]
Just tested on Windows Chrome, Android Chrome and IOS Safari. It works everywhere! Thanks!!
